"""
Trainable Neural Reward Model for Service Composition.

Learns to predict composition rewards from text representations using the
Bradley–Terry preference framework.  Trained on (chosen, rejected) pairs
generated by ``RewardDatasetBuilder``, where the analytical
``RewardCalculator`` provides automatic ground-truth labels — no human
annotation required.

The trained model maps an LLM-generated composition description to a scalar
reward, enabling PPO / GRPO in Phase 3.

Part of: QSRT — QoS-Driven Reinforcement Fine-Tuning with Social Trust Rewards
Phase 2: Reward Model Training

Architecture:
    Composition text ──► Tokenizer ──► Frozen base LM ──► LoRA adapters
                                                              │
                                                        Reward Head (Linear)
                                                              │
                                                         Scalar reward ∈ ℝ

Loss:  -log σ( r(chosen) - r(rejected) )    (Bradley–Terry)

Copyright (c) 2026. All rights reserved.
"""

from __future__ import annotations

import os
import json
import time
from typing import Dict, Any, Optional, List

# ---------------------------------------------------------------------------
# Lazy imports
# ---------------------------------------------------------------------------
_TORCH_AVAILABLE = False
_HF_AVAILABLE = False
_PEFT_AVAILABLE = False

try:
    import torch
    import torch.nn as nn
    _TORCH_AVAILABLE = True
except ImportError:
    pass

try:
    from transformers import AutoTokenizer, AutoModel
    _HF_AVAILABLE = True
except ImportError:
    pass

try:
    from peft import LoraConfig, get_peft_model, PeftModel, TaskType
    _PEFT_AVAILABLE = True
except ImportError:
    pass


def _deps_available() -> bool:
    return _TORCH_AVAILABLE and _HF_AVAILABLE and _PEFT_AVAILABLE


def _missing_packages() -> List[str]:
    m = []
    if not _TORCH_AVAILABLE:
        m.append("torch")
    if not _HF_AVAILABLE:
        m.append("transformers")
    if not _PEFT_AVAILABLE:
        m.append("peft")
    return m


# ═══════════════════════════════════════════════════════════════════════
# Reward Head network (tiny trainable layer on top of the LM)
# ═══════════════════════════════════════════════════════════════════════

if _TORCH_AVAILABLE:
    class _RewardHead(nn.Module):
        """Projects the last hidden state to a scalar reward."""

        def __init__(self, hidden_size: int, dropout: float = 0.1):
            super().__init__()
            self.dense = nn.Linear(hidden_size, hidden_size)
            self.activation = nn.GELU()
            self.dropout = nn.Dropout(dropout)
            self.out_proj = nn.Linear(hidden_size, 1)

        def forward(self, last_hidden: torch.Tensor) -> torch.Tensor:
            """
            Args:
                last_hidden: (batch, hidden_size)  – CLS / last-token repr
            Returns:
                (batch,) scalar rewards
            """
            x = self.dense(last_hidden)
            x = self.activation(x)
            x = self.dropout(x)
            x = self.out_proj(x)
            return x.squeeze(-1)


# ═══════════════════════════════════════════════════════════════════════
# Reward Model Trainer
# ═══════════════════════════════════════════════════════════════════════

class RewardModelTrainer:
    """
    Trains a neural reward model using Bradley–Terry preference loss.

    The model consists of:
    1. A frozen causal / encoder LM backbone
    2. LoRA adapters (small trainable delta)
    3. A reward head (Linear → scalar)

    Training data = preference pairs from ``RewardDatasetBuilder``:
        { "chosen": {..., "service_ids": [...]},
          "rejected": {..., "service_ids": [...]},
          "reward_margin": 0.15, ... }

    Loss = -log σ( r_chosen - r_rejected )   (Bradley–Terry)
    """

    DEFAULT_CONFIG = {
        "model_name": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "lora_r": 8,
        "lora_alpha": 16,
        "lora_dropout": 0.05,
        "learning_rate": 1e-4,
        "num_epochs": 3,
        "batch_size": 4,
        "max_seq_length": 512,
        "weight_decay": 0.01,
        "warmup_ratio": 0.1,
        "margin_weight": 1.0,      # λ for margin-aware loss
    }

    def __init__(
        self,
        config: Optional[Dict[str, Any]] = None,
        output_dir: Optional[str] = None,
    ):
        if not _deps_available():
            raise ImportError(
                f"Reward model requires: {', '.join(_missing_packages())}. "
                f"Install with: pip install {' '.join(_missing_packages())}"
            )

        self.config = {**self.DEFAULT_CONFIG, **(config or {})}
        self.output_dir = output_dir or os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "models", "reward_model",
        )

        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model = None
        self.reward_head = None
        self.tokenizer = None
        self.is_trained = False
        self.training_metrics: Dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Availability
    # ------------------------------------------------------------------

    @staticmethod
    def is_available() -> bool:
        return _deps_available()

    @staticmethod
    def missing_packages() -> List[str]:
        return _missing_packages()

    # ------------------------------------------------------------------
    # Text representation of a composition
    # ------------------------------------------------------------------

    @staticmethod
    def composition_to_text(
        service_ids: List[str],
        service_dict: Dict,
        request_data: Dict,
    ) -> str:
        """
        Serialize a composition into a text prompt the reward model can score.
        """
        lines = [f"Request: produce '{request_data.get('resultant', '?')}'"]

        provided = request_data.get("provided", [])
        lines.append(f"Provided: {len(provided)} params")

        qos = request_data.get("qos_constraints", {})
        if qos:
            parts = []
            for key in ("ResponseTime", "Reliability", "Availability"):
                v = qos.get(key, 0)
                if v:
                    parts.append(f"{key}={v}")
            if parts:
                lines.append(f"Constraints: {', '.join(parts)}")

        lines.append(f"Composition ({len(service_ids)} services):")
        for sid in service_ids:
            svc = service_dict.get(sid)
            if svc:
                qos_str = (
                    f"rel={svc.qos.reliability:.1f}% "
                    f"rt={svc.qos.response_time:.0f}ms "
                    f"avl={svc.qos.availability:.1f}%"
                )
                trust_str = ""
                if hasattr(svc, "annotations") and svc.annotations:
                    sn = svc.annotations.social_node
                    trust_str = (
                        f" trust={sn.trust_degree.value:.2f}"
                        f" rep={sn.reputation.value:.2f}"
                        f" coop={sn.cooperativeness.value:.2f}"
                    )
                lines.append(f"  {sid}: {qos_str}{trust_str}")
            else:
                lines.append(f"  {sid}: (unknown)")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def train(
        self,
        preference_pairs: List[Dict[str, Any]],
        service_dict: Dict,
        progress_callback=None,
    ) -> Dict[str, Any]:
        """
        Train the reward model on preference pairs.

        Args:
            preference_pairs: output of RewardDatasetBuilder.build_preference_pairs()
            service_dict: {id: WebService} mapping
            progress_callback: optional callable(step, total, metrics)

        Returns:
            dict with training metrics
        """
        start = time.time()
        cfg = self.config

        print(f"\n{'=' * 60}")
        print("PHASE 2 — Reward Model Training (Bradley–Terry)")
        print(f"{'=' * 60}")
        print(f"  Model       : {cfg['model_name']}")
        print(f"  Device      : {self.device}")
        print(f"  Pairs       : {len(preference_pairs)}")
        print(f"  LoRA rank   : {cfg['lora_r']}")
        print(f"  Epochs      : {cfg['num_epochs']}")
        print(f"  LR          : {cfg['learning_rate']}")
        print(f"  Output dir  : {self.output_dir}")
        print(f"{'=' * 60}\n")

        # 1. Tokenizer
        print("[RM 1/5] Loading tokenizer …")
        self.tokenizer = AutoTokenizer.from_pretrained(
            cfg["model_name"], trust_remote_code=True,
        )
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id

        # 2. Base model + LoRA
        print("[RM 2/5] Loading base model + LoRA …")
        dtype = torch.float16 if self.device == "cuda" else torch.float32
        base = AutoModel.from_pretrained(
            cfg["model_name"],
            torch_dtype=dtype,
            trust_remote_code=True,
        )
        if self.device == "cpu":
            base = base.to("cpu")
        else:
            base = base.to("cuda")

        lora_cfg = LoraConfig(
            r=cfg["lora_r"],
            lora_alpha=cfg["lora_alpha"],
            lora_dropout=cfg["lora_dropout"],
            target_modules=["q_proj", "v_proj"],
            bias="none",
            task_type=TaskType.FEATURE_EXTRACTION,
        )
        self.model = get_peft_model(base, lora_cfg)

        trainable, total = self.model.get_nb_trainable_parameters()
        print(f"  LoRA params: {trainable:,} / {total:,} "
              f"({100 * trainable / total:.2f}%)")

        # 3. Reward head
        print("[RM 3/5] Initialising reward head …")
        hidden_size = base.config.hidden_size
        self.reward_head = _RewardHead(hidden_size).to(
            self.device, dtype=dtype
        )

        # 4. Prepare data
        print("[RM 4/5] Encoding preference pairs …")
        chosen_texts, rejected_texts, margins = [], [], []
        for pair in preference_pairs:
            c_ids = pair["chosen"]["service_ids"]
            r_ids = pair["rejected"]["service_ids"]
            req = pair.get("request", {})

            chosen_texts.append(
                self.composition_to_text(c_ids, service_dict, req)
            )
            rejected_texts.append(
                self.composition_to_text(r_ids, service_dict, req)
            )
            margins.append(pair["reward_margin"])

        # 5. Training loop
        print("[RM 5/5] Training …\n")
        self.model.train()
        self.reward_head.train()

        all_params = (
            list(self.model.parameters())
            + list(self.reward_head.parameters())
        )
        optimizer = torch.optim.AdamW(
            all_params,
            lr=cfg["learning_rate"],
            weight_decay=cfg["weight_decay"],
        )

        n = len(preference_pairs)
        bs = cfg["batch_size"]
        total_steps = cfg["num_epochs"] * ((n + bs - 1) // bs)
        warmup_steps = int(total_steps * cfg["warmup_ratio"])
        step = 0
        epoch_losses = []

        for epoch in range(cfg["num_epochs"]):
            # Shuffle
            import random
            indices = list(range(n))
            random.shuffle(indices)

            running_loss = 0.0
            batch_count = 0

            for i in range(0, n, bs):
                batch_idx = indices[i: i + bs]

                # Tokenize chosen & rejected
                c_batch = [chosen_texts[j] for j in batch_idx]
                r_batch = [rejected_texts[j] for j in batch_idx]
                m_batch = torch.tensor(
                    [margins[j] for j in batch_idx],
                    device=self.device, dtype=dtype,
                )

                c_enc = self.tokenizer(
                    c_batch, return_tensors="pt", truncation=True,
                    max_length=cfg["max_seq_length"], padding=True,
                )
                r_enc = self.tokenizer(
                    r_batch, return_tensors="pt", truncation=True,
                    max_length=cfg["max_seq_length"], padding=True,
                )

                c_enc = {k: v.to(self.device) for k, v in c_enc.items()}
                r_enc = {k: v.to(self.device) for k, v in r_enc.items()}

                # Forward
                with torch.cuda.amp.autocast(enabled=(self.device == "cuda")):
                    c_out = self.model(**c_enc)
                    r_out = self.model(**r_enc)

                    # Use last token hidden states as representation
                    c_hidden = c_out.last_hidden_state[:, -1, :]
                    r_hidden = r_out.last_hidden_state[:, -1, :]

                    c_reward = self.reward_head(c_hidden)
                    r_reward = self.reward_head(r_hidden)

                    # Bradley–Terry loss with margin awareness
                    # L = -log σ( r_c - r_r - margin * λ )
                    diff = c_reward - r_reward
                    margin_term = m_batch * cfg["margin_weight"]
                    loss = -torch.nn.functional.logsigmoid(
                        diff - margin_term
                    ).mean()

                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(all_params, 1.0)
                optimizer.step()

                running_loss += loss.item()
                batch_count += 1
                step += 1

                if progress_callback and step % max(total_steps // 20, 1) == 0:
                    progress_callback(
                        step=step,
                        total=total_steps,
                        metrics={
                            "loss": loss.item(),
                            "epoch": epoch + 1,
                        },
                    )

            avg_loss = running_loss / max(batch_count, 1)
            epoch_losses.append(avg_loss)
            print(f"  Epoch {epoch + 1}/{cfg['num_epochs']}  "
                  f"loss={avg_loss:.4f}")

        # Save
        os.makedirs(self.output_dir, exist_ok=True)
        adapter_path = os.path.join(self.output_dir, "lora_adapter")
        self.model.save_pretrained(adapter_path)
        self.tokenizer.save_pretrained(adapter_path)

        head_path = os.path.join(self.output_dir, "reward_head.pt")
        torch.save(self.reward_head.state_dict(), head_path)

        cfg_path = os.path.join(self.output_dir, "config.json")
        with open(cfg_path, "w") as f:
            json.dump({
                "config": self.config,
                "hidden_size": hidden_size,
                "num_pairs": len(preference_pairs),
            }, f, indent=2)

        elapsed = time.time() - start
        self.is_trained = True
        self.training_metrics = {
            "final_loss": round(epoch_losses[-1], 6) if epoch_losses else 0,
            "epoch_losses": [round(l, 6) for l in epoch_losses],
            "total_steps": step,
            "training_time_seconds": round(elapsed, 2),
            "num_pairs": len(preference_pairs),
            "lora_params": trainable,
            "head_params": sum(p.numel() for p in self.reward_head.parameters()),
            "device": self.device,
            "output_dir": self.output_dir,
        }

        print(f"\n{'=' * 60}")
        print("REWARD MODEL TRAINING COMPLETE")
        print(f"{'=' * 60}")
        print(f"  Final loss : {self.training_metrics['final_loss']:.6f}")
        print(f"  Steps      : {step}")
        print(f"  Time       : {elapsed:.1f} s")
        print(f"  Saved to   : {self.output_dir}")
        print(f"{'=' * 60}\n")

        return self.training_metrics

    # ------------------------------------------------------------------
    # Inference
    # ------------------------------------------------------------------

    def predict_reward(
        self,
        service_ids: List[str],
        service_dict: Dict,
        request_data: Dict,
    ) -> float:
        """
        Predict the reward for a single composition.

        Returns:
            Scalar reward value (unbounded, higher = better).
        """
        if not self.is_trained:
            raise RuntimeError(
                "Reward model not trained. Call train() or load() first."
            )

        text = self.composition_to_text(service_ids, service_dict, request_data)
        enc = self.tokenizer(
            text, return_tensors="pt", truncation=True,
            max_length=self.config["max_seq_length"],
        )
        enc = {k: v.to(self.device) for k, v in enc.items()}

        self.model.eval()
        self.reward_head.eval()
        with torch.no_grad():
            out = self.model(**enc)
            hidden = out.last_hidden_state[:, -1, :]
            reward_val = self.reward_head(hidden)

        return float(reward_val.item())

    def rank_compositions(
        self,
        compositions: List[List[str]],
        service_dict: Dict,
        request_data: Dict,
    ) -> List[Dict[str, Any]]:
        """
        Rank multiple compositions by predicted reward.

        Args:
            compositions: list of service-id lists
            service_dict: {id: WebService}
            request_data: request dict

        Returns:
            Sorted list of {"service_ids": [...], "predicted_reward": float}
        """
        results = []
        for comp in compositions:
            r = self.predict_reward(comp, service_dict, request_data)
            results.append({"service_ids": comp, "predicted_reward": r})
        results.sort(key=lambda x: x["predicted_reward"], reverse=True)
        return results

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def load(self, path: Optional[str] = None) -> bool:
        """Load a previously saved reward model from disk."""
        path = path or self.output_dir
        cfg_path = os.path.join(path, "config.json")
        if not os.path.exists(cfg_path):
            print(f"[RM] No reward model at {path}")
            return False

        with open(cfg_path) as f:
            saved = json.load(f)
        self.config.update(saved.get("config", {}))
        hidden_size = saved.get("hidden_size", 2048)

        adapter_path = os.path.join(path, "lora_adapter")
        self.tokenizer = AutoTokenizer.from_pretrained(
            adapter_path, trust_remote_code=True,
        )
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        dtype = torch.float16 if self.device == "cuda" else torch.float32
        base = AutoModel.from_pretrained(
            self.config["model_name"],
            torch_dtype=dtype,
            trust_remote_code=True,
        )
        self.model = PeftModel.from_pretrained(base, adapter_path)
        self.model = self.model.to(self.device)

        self.reward_head = _RewardHead(hidden_size).to(self.device, dtype=dtype)
        head_path = os.path.join(path, "reward_head.pt")
        self.reward_head.load_state_dict(
            torch.load(head_path, map_location=self.device)
        )

        self.is_trained = True
        print(f"[RM] Reward model loaded from {path} ✓")
        return True

    def get_metrics(self) -> Dict[str, Any]:
        return self.training_metrics
