"""
WSDL Enricher - Enrichissement du WSDL avec annotations sémantiques
"""
from lxml import etree
import os
from datetime import datetime

class WSDLEnricher:
    """Classe pour enrichir un WSDL avec des annotations sémantiques"""
    
    NAMESPACES = {
        'wsdl': 'http://schemas.xmlsoap.org/wsdl/',
        'soap': 'http://schemas.xmlsoap.org/wsdl/soap/',
        'xsd': 'http://www.w3.org/2001/XMLSchema',
        'soap12': 'http://schemas.xmlsoap.org/wsdl/soap12/',
        'semantic': 'http://example.com/semantic-annotations'  # Notre namespace custom
    }
    
    def __init__(self, wsdl_path):
        """
        Initialise l'enrichisseur
        
        Args:
            wsdl_path (str): Chemin vers le fichier WSDL original
        """
        self.wsdl_path = wsdl_path
        self.tree = None
        self.root = None
        
    def enrich(self, annotations, output_path):
        """
        Enrichit le WSDL avec les annotations et sauvegarde
        
        Args:
            annotations (dict): Annotations générées par le LLM
            output_path (str): Chemin de sortie pour le WSDL enrichi
            
        Returns:
            str: Chemin du fichier généré
        """
        # Charger le WSDL
        self.tree = etree.parse(self.wsdl_path)
        self.root = self.tree.getroot()
        
        # Ajouter le namespace sémantique
        self.root.set(f"{{{etree.QName(self.root).namespace}}}semantic", 
                      self.NAMESPACES['semantic'])
        
        # Enrichir les différentes parties
        self._add_service_annotations(annotations)
        self._add_operation_annotations(annotations)
        self._add_metadata_section(annotations)
        
        # Sauvegarder
        self._save_enriched_wsdl(output_path)
        
        return output_path
    
    def _add_service_annotations(self, annotations):
        """Ajoute les annotations globales au service"""
        # Trouver l'élément service
        service = self.root.find('.//wsdl:service', self.NAMESPACES)
        
        if service is not None:
            # Ajouter un élément documentation si absent
            doc = service.find('wsdl:documentation', self.NAMESPACES)
            if doc is None:
                doc = etree.SubElement(service, '{http://schemas.xmlsoap.org/wsdl/}documentation')
            
            # Construire la documentation enrichie
            doc_text = f"""
Service Annotations (Generated by Semantic Annotator on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')})

Domain: {annotations.get('domain', 'N/A')}
Description: {annotations.get('description', 'N/A')}
Keywords: {', '.join(annotations.get('keywords', []))}

Use Cases:
{self._format_list(annotations.get('use_cases', []))}
"""
            doc.text = doc_text.strip()
            
            # Ajouter des attributs personnalisés
            ns_semantic = '{' + self.NAMESPACES['semantic'] + '}'
            service.set(f'{ns_semantic}domain', annotations.get('domain', 'unknown'))
            service.set(f'{ns_semantic}keywords', ','.join(annotations.get('keywords', [])))
    
    def _add_operation_annotations(self, annotations):
        """Ajoute les annotations aux opérations"""
        operations_annotations = annotations.get('operations', [])
        
        # Trouver toutes les opérations dans portType
        port_types = self.root.findall('.//wsdl:portType', self.NAMESPACES)
        
        for port_type in port_types:
            operations = port_type.findall('.//wsdl:operation', self.NAMESPACES)
            
            for operation in operations:
                op_name = operation.get('name', '')
                
                # Trouver l'annotation correspondante
                op_annotation = next(
                    (ann for ann in operations_annotations if ann.get('name') == op_name),
                    None
                )
                
                if op_annotation:
                    # Ajouter documentation
                    doc = operation.find('wsdl:documentation', self.NAMESPACES)
                    if doc is None:
                        doc = etree.SubElement(operation, '{http://schemas.xmlsoap.org/wsdl/}documentation')
                    
                    doc_text = f"""
Operation: {op_name}
{op_annotation.get('semantic_description', 'N/A')}

Input Semantic: {op_annotation.get('input_semantic', 'N/A')}
Output Semantic: {op_annotation.get('output_semantic', 'N/A')}
"""
                    doc.text = doc_text.strip()
                    
                    # Ajouter attributs sémantiques
                    ns_semantic = '{' + self.NAMESPACES['semantic'] + '}'
                    operation.set(f'{ns_semantic}description', 
                                op_annotation.get('semantic_description', ''))
    
    def _add_metadata_section(self, annotations):
        """Ajoute une section metadata complète au début du WSDL"""
        # Créer l'élément metadata
        ns_wsdl = '{http://schemas.xmlsoap.org/wsdl/}'
        
        # Chercher si documentation existe déjà au niveau racine
        root_doc = self.root.find('wsdl:documentation', self.NAMESPACES)
        
        if root_doc is None:
            # Insérer au début (après la balise definitions)
            root_doc = etree.Element(f'{ns_wsdl}documentation')
            self.root.insert(0, root_doc)
        
        # Construire le contenu metadata
        metadata_content = f"""
=============================================================================
SEMANTIC ANNOTATIONS
=============================================================================
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Tool: Intelligent Web Services Composition - Semantic Annotator

SERVICE METADATA
----------------
Domain: {annotations.get('domain', 'N/A')}
Description: {annotations.get('description', 'N/A')}
Keywords: {', '.join(annotations.get('keywords', []))}

USE CASES
---------
{self._format_list(annotations.get('use_cases', []))}

OPERATIONS SUMMARY
------------------
{self._format_operations_summary(annotations.get('operations', []))}

=============================================================================
"""
        root_doc.text = metadata_content.strip()
    
    def _format_list(self, items):
        """Formate une liste pour la documentation"""
        if not items:
            return "- None"
        return '\n'.join([f"- {item}" for item in items])
    
    def _format_operations_summary(self, operations):
        """Formate le résumé des opérations"""
        if not operations:
            return "No operations annotated"
        
        summary = []
        for op in operations:
            summary.append(f"• {op.get('name', 'N/A')}: {op.get('semantic_description', 'N/A')}")
        
        return '\n'.join(summary)
    
    def _save_enriched_wsdl(self, output_path):
        """Sauvegarde le WSDL enrichi"""
        # Écrire avec un formatage propre
        self.tree.write(
            output_path,
            encoding='utf-8',
            xml_declaration=True,
            pretty_print=True
        )
        
        print(f"✅ WSDL enrichi sauvegardé : {output_path}")
    
    def get_enriched_content(self):
        """Retourne le contenu du WSDL enrichi en string"""
        if self.tree is None:
            return None
        
        return etree.tostring(
            self.tree,
            encoding='utf-8',
            xml_declaration=True,
            pretty_print=True
        ).decode('utf-8')